home/urls.py
from django.urls import path
from .views import HomePageView, ContactPageView, AboutPageView, PortfolioView, OurTeamPageView, MoreView
from . import views
app_name="home"
urlpatterns = [
    path('', HomePageView.as_view(),name="home"),
    # path('portfolio/', PortfolioView.as_view(),name="portfolio"),
    path('portfolio/', views.PortfolioView, name='portfolio'),
    path('more/', MoreView.as_view(),name="more"),
    path('team/', OurTeamPageView.as_view(),name="team"),
    path('contact-us/', ContactPageView.as_view(),name="contact-us"),
    # path('contact-us/', views.ContactPageView, name="contact-us"),
    path('about/', AboutPageView.as_view(),name="about"),
]

thycha/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from .import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
import os,datetime
from django.core.exceptions import ValidationError
from thycha.settings import MEDIA_ROOT

def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 4.0
    if filesize > megabyte_limit*1024*1024:
        raise ValidationError("Max file size is %sMB" % str(megabyte_limit))
    
# Create your models here.
class PortfolioMaster(models.Model):
    id = models.CharField(primary_key=True,max_length=50)
    # id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=15,default='all',choices=[('All','All'),('Print','Print'),('Packaging','Packaging'),('Illustration','Illustration'),('Digital','Digital'),('Branding','Branding')])
    desc = models.TextField(null=True,blank=True)
    thumbnailimage = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image1 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image2 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image3 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image4 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image5 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image6 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image7 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')
    image8 = models.ImageField(upload_to ='uploads/',validators=[validate_image], blank=True, null=True,help_text='Maximum file size allowed is 4Mb')

    class Meta:
        db_table = "PORTFOLIOMASTER"
    def __str__(self):
        return self.id+' '+self.name
    def save(self, *args, **kwargs):
        
        try:
            if self.id:
                id_instance = PortfolioMaster.objects.get(id = self.id)
                if id_instance.upload != self.upload:
                    try:
                        os.remove(MEDIA_ROOT+str(id_instance.upload))
                    except:
                        pass
        except:
            pass
        super().save(*args, **kwargs)
    

home/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.generic import TemplateView,View
from .models import (PortfolioMaster)
from django.core.mail import send_mail
from django.contrib import messages

# Create your views here.
class HomePageView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        
        return context
    
class ContactPageView(TemplateView):
    template_name = "contact.html"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        
        return context
# def ContactPageView(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         c_name = request.POST.get('c-name')
#         telno = request.POST.get('telno')
#         subject = request.POST.get('subject')
#         messageContent = request.POST.get('message')
        
#         data = {
#             'name': name,
#             'email': email,
#             'c_name': c_name,
#             'telno': telno,
#             'subject': subject,
#             'message': messageContent
#         }
        
#         print(data)
#         message = '''
#         Message: {}

#         From: {}
#         Name: {}
#         Company Name: {}
#         Contact No.: {}

#         '''.format(data['message'],data['email'],data['name'],data['c_name'],data['telno'])
#         try:
#             if(send_mail(data['subject'], message, '', ['faketest4410@gmail.com'])):
#                 messages.success(request, 'Thanks for contacting! We will get in touch with you soon')
#                 data = {}
#             else:
#                 messages.success(request, 'Not Allowed')
#             # return render(request, 'contact.html', context={messages})
#             return HttpResponseRedirect('/contact-us')
#         except:
#             messages.success(request, 'Something Went Wrong!, Please try again after sometime or use whatsapp')
#         data = {}
#     return render(request, "contact.html", {})
class AboutPageView(TemplateView):
    template_name = "about.html"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        
        return context
    
class OurTeamPageView(TemplateView):
    template_name = "team.html"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        
        return context

# class PortfolioView(TemplateView):
#     template_name = "portfolio.html"
#     def post(self, request):
#         context = {}
#         # itemlist = PortfolioMaster.objects.values('id','id__id','id__name','id__name','id__desc','id__thumbnailimage')
#         itemlist = PortfolioMaster.objects.all()
#         context = {
#             'itemlist':itemlist.distinct()
#         }
#         html = render_to_string('portfolio.html',context)
#         return JsonResponse({'STATUS':1,'html':html})

def PortfolioView(request):
    itemlist = PortfolioMaster.objects.all()
    return render(request, "portfolio.html", {"itemlist":itemlist})
    
class MoreView(TemplateView):
    template_name = "render/more.html"
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        
        try:
            context['item'] = PortfolioMaster.objects.filter(id=self.request.GET.get('item')).values('image1','image2','image3','image4','image5','image6','image7','image8')[0]
        except:
            pass
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %}{% endblock %}</title>
    <meta name="title" content="Thycha Creatives">
    <meta content="We are an advertising agency which creates social media content, digital marketing, branding and many more services as per the customized demand. " name="description">
    <meta content="top google marketing agency,agency marketing online,internet marketing advertising agency,digital marketing services to offer ,social media marketing company ,digital seo,top online marketing firms ,successful marketing agencies,the best digital agency,cheap digital marketing company, top rated marketing companies,seo & content marketing agency,social branding agency,largest social media marketing companies, creating a social media marketing agency, best way to social media marketing,media marketing packages,social media marketing firms in india, google ads and adwords,get certified google ads,seo search website,it digital agency,website development and digital marketing company ,best social media marketing agency in india,social media marketing company near me,digital marketing and web development company, on page optimization and off page optimization,online marketing companies in kerala" name="keywords">

     <!-- Open Graph / Facebook -->
     <meta property="og:type" content="website">
     <meta property="og:url" content="https://thychacreatives.com/">
     <meta property="og:title" content="Thycha Creatives">
     <meta property="og:description" content="We are an advertising agency which creates social media content, digital marketing, branding and many more services as per the customized demand.">
     
    <!-- Favicons -->
    <!-- <link href="{% static 'img/logo/logo-dark.png' %}" rel="icon"> -->
    <!-- <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon"> -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/logo/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/logo/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/logo/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/logo/favicon/site.webmanifest' %}">

    <!-- Google Fonts -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,100,0,200" />

    <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet"> -->
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <!--Floating WhatsApp css-->
    <link rel="stylesheet"
        href="https://rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.css">
    <!--Floating WhatsApp javascript-->
    <script type="text/javascript"
        src="https://rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.js"></script>
    {% block extra_style %}

    {% endblock extra_style %}
</head>

<body>

    {% include 'navbar.html' %}

    {% block pagecontent %}

    {% endblock pagecontent %}

    {% include 'footer.html' %}


    <div id="preloader"></div>
    <a href="#">
        <div id="WAButton"></div>
    </a>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">
        <i class="icon-double-angle-up"></i>
    </a>
    <!-- <div class="scroll-to-top scroll-to-target thm-bg-clr" data-target="html"><span class="fa fa-angle-up"></span></div> -->

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static '/js/particles.js' %}"></script>
    <script src="{% static '/js/app.js' %}"></script>



    <script src="https://cdn.jsdelivr.net/npm/animejs@3.1.0/lib/anime.min.js"></script>
    <script src="{% static 'glightbox/demo/js/valde.min.js' %}"></script>
    <script src="{% static 'glightbox/dist/js/glightbox.js' %}"></script>
    <script src="{% static 'glightbox/demo/js/site.js' %}"></script>
    <script>
        var lightbox = GLightbox();
        lightbox.on('open', (target) => {
            console.log('lightbox opened');
        });
        var lightboxDescription = GLightbox({
            selector: '.glightbox2'
        });
        var lightboxVideo = GLightbox({
            selector: '.glightbox3'
        });
        lightboxVideo.on('slide_changed', ({ prev, current }) => {
            console.log('Prev slide', prev);
            console.log('Current slide', current);

            const { slideIndex, slideNode, slideConfig, player } = current;

            if (player) {
                if (!player.ready) {
                    // If player is not ready
                    player.on('ready', (event) => {
                        // Do something when video is ready
                    });
                }

                player.on('play', (event) => {
                    console.log('Started play');
                });

                player.on('volumechange', (event) => {
                    console.log('Volume change');
                });

                player.on('ended', (event) => {
                    console.log('Video ended');
                });
            }
        });

        var lightboxInlineIframe = GLightbox({
            selector: '.glightbox4'
        });

        /* var exampleApi = GLightbox({ selector: null });
        exampleApi.insertSlide({
            href: 'https://picsum.photos/1200/800',
        });
        exampleApi.insertSlide({
            width: '500px',
            content: '<p>Example</p>'
        });
        exampleApi.insertSlide({
            href: 'https://www.youtube.com/watch?v=WzqrwPhXmew',
        });
        exampleApi.insertSlide({
            width: '200vw',
            content: document.getElementById('inline-example')
        });
        exampleApi.open(); */
    </script>
    <script>$(document).ready(function () {
            $(".filter-button").click(function () {
                var value = $(this).attr("data-filter");
                //   console.log("click");
                if (value == "All") {
                    $(".filter").removeClass("disable");
                    $(".filter").show("1000");
                } else {
                    //            $('.filter[filter-item="'+value+'"]').removeClass('hidden');
                    //            $(".filter").not('.filter[filter-item="'+value+'"]').addClass('hidden');
                    $(".filter").removeClass("disable");
                    $(".filter")
                        .not("." + value)
                        .addClass("disable");
                    $(".filter")
                        .filter("." + value)
                        .show("3000");
                }
            });

            if ($(".filter-button").removeClass("active")) {
                $(this).removeClass("active");
                $(this).removeClass("disable");
            }
            $(this).addClass("active");
        });
    </script>
</body>

</html>

templates/footer.html
<footer id="footer">
    {% load static %}
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-5 col-md-4">
                    <div class="footer-info">
                        <!-- <h3>Thycha Creatives</h3> -->
                        <div class="logoimg">
                            <img src="{% static 'img/logo/Thycha-Logo.png' %}" alt="">
                        </div>
                        <p>
                        <div class="address pl-5">
                            <i class="icon-map-marker pr-1"></i>
                            Location: <br> <br><span style="font-weight: 900;">CORPORATE ADDRESS</span>
                            <p class="pt-1">CP-11/83 Kadiyangad palam.Changaroth, <br>Kozhikode , Kerala ,India
                                -673525</p>

                            <br> <span style="font-weight: 900;">WORKING ADDRESS</span>

                            <p class="pt-1">#1102, Level 1, HILITE Business Park, <br> Kozhikode, Kerala, India
                                - 673014 </p>
                        </div>
                        <br>
                        <div class="open-hours">
                            <i class="icon-time pr-1"></i>
                            Open Hours:
                            <p>
                                Monday-Sunday:<br> 9.00 am to 9.00 pm
                            </p>
                        </div>
                        <br>

                        </p>

                    </div>
                </div>

                <div class="col-lg-4 col-md-4 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="icon-angle-right"></i><a h4 href="{% url 'home:home'%}">Home</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="{% url 'home:about'%}">About us</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="{% url 'home:team'%}">Team</a></li>
                        <!--  <li><i class="icon-angle-right"></i> <a h4 href="#">Terms of service</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="#">Privacy policy</a></li> -->
                    </ul>
                </div>

                <div class="col-lg-3 col-md-4 footer-links">
                    <h4>Connect With Us</h4>
                    <ul>

                        <!-- <li><i class="icon-angle-right"></i> <a h4 href="#">Marketing</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="#">Graphic Design</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="#">Marketing</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="#">Graphic Design</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="#">Marketing</a></li>
                        <li><i class="icon-angle-right"></i> <a h4 href="#">Graphic Design</a></li> -->
                        <div class="email">
                            <i class="icon-envelope-alt pr-1"></i>
                            Email:
                            <a href="mailto: thychacreatives@gmail.com">thychacreatives@gmail.com</a>

                        </div>
                        <br>
                        <div class="phone">
                            <i class="icon-phone pr-1"></i>
                            Call:
                            <p>8089265880 , 8089227880</p>

                        </div>
                        <div class="social-links mt-3">
                            <a href="https://www.facebook.com/thychacreatives" class="facebook"><i class="icon-facebook"></i></a>
                            <a href="https://www.instagram.com/thycha_creatives/" class="instagram"><i class="icon-instagram"></i></a>
                            <a href="https://www.linkedin.com/company/thycha-creatives/" class="linkedin"><i class="icon-linkedin"></i></a>
                        </div>

                    </ul>
                </div>

                <!-- <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4 h4>Our Newsletter</h4>
                    <p h4>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit" value="Subscribe" h4>
                    </form>
                </div> -->

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright ">
            &copy; Copyright <strong><span>Thycha Creatives</span></strong>. All Rights Reserved
        </div>

    </div>
</footer>

templates/navbar.html
<header id="header" class="fixed-top d-flex align-items-center"> {% load static %}
    <div class="container-fluid  d-flex align-items-center justify-content-lg-between">
        <a href="{% url 'home:home'%}" class="logo me-auto me-lg-0"><img src="{% static 'img/logo/Thycha Logo White.png' %}" alt=""
                class="img-fluid"></a>

        <!-- <nav id="navbar" class="navbar order-last order-lg-0 ">
                <ul>
                    <li><a class="nav-link scrollto active  " href="index.html">Home</a></li>
                    <li><a class="nav-link scrollto  " href="About.html">About</a></li>
                    <li><a class="nav-link scrollto  " href="contact.html">Contact</a></li>
                </ul>
                <i class="icon-reorder mobile-nav-toggle p-2"></i>
            </nav> -->

        <nav>

            <ul>
                <li><a class="nav-link scrollto active  " href="{% url 'home:home'%}">Home</a></li>
                <li><a class="nav-link scrollto  " href="{% url 'home:about'%}">About</a></li>
                <li><a class="nav-link scrollto  " href="{% url 'home:team'%}">Team</a></li>
                <li><a class="nav-link scrollto  " href="{% url 'home:portfolio'%}">Portfolio</a></li>
                <li><a class="nav-link scrollto  " href="{% url 'home:contact-us'%}">Contact</a></li>
            </ul>
            <div class="menu-bars">
                <input type="checkbox">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </nav>
        <!-- .navbar -->


    </div>
</header>
<!-- End Header -->

templates/portfolio.html
{% extends 'base.html' %}{% load static %}
{% block title %} Thycha Creatives | Portfolio{% endblock %}
{% block pagecontent %}



<!-- ======= Gallery Section ======= -->
<section id="hero" class="gallery " style="padding-top: 200px;">

    <div class="container" data-aos="fade-up">
        <div class="text-center mx-auto wow fadeInUp " data-wow-delay="0.1s">
            <h1 class="text-uppercase " style="font-size: 40px;">Portfolio</h1>
        </div>
        <div class="text-center align-items-center">

            <a class="btn filter-button " data-filter="All"><span class="material-symbols-outlined p-3">
                    apps <h6 h4>All</h6></a>
            </span>
            <a class="btn filter-button " data-filter="Print"><span class="material-symbols-outlined p-3">
                    print<h6 h4>print</h6></a>
            </span>
            <a class="btn filter-button " data-filter="Packaging"><span class="material-symbols-outlined p-3">
                    package<h6 h4>Packaging</h6></a>
            </span>
            <!-- <a class="btn filter-button " data-filter="Illustration"><span class="material-symbols-outlined p-3">
                    draw<h6 h4>Illustration</h6></a>
            </span> -->
            <a class="btn filter-button " data-filter="Digital-"><span class="material-symbols-outlined p-3">
                    auto_awesome_mosaic<h6 h4>Digital</h6></a>
            </span>
            <a class="btn filter-button " data-filter="Branding"><span class="material-symbols-outlined p-3">
                    glyphs<h6 h4>Branding</h6></a>
            </span>
        </div>
    </div>
    <div class="container-fluid" data-aos="fade-up">

        <div class="row g-0">

            <!-- Images with description example -->
            <!-- <section class="section pair">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                            </div>
                        </div>
                    </div>
                </section> -->

            {% for i in itemlist %}
            <div class="col-lg-3 col-md-4 filter {{i.category}}">
                <div class="gallery-item">
                    <ul class="box-container">

                        <li class="box">
                            <div class="inner">
                                <a href="{{i.thumbnailimage.url}}" class="glightbox2"
                                    data-glightbox="title: {{i.name}}; description: .custom-desc{{i.id}}; descPosition: right;">
                                    <img src="{{i.thumbnailimage.url}}" alt="image" />
                                </a>

                                <div class="glightbox-desc custom-desc{{i.id}}">
                                    <p>
                                        <!-- You can set the position of the description in different ways for example -->
                                        <strong style="text-decoration: underline">{{i.category}}</strong>
                                    </p>
                                    <p>
                                        {{i.desc|linebreaks}}
                                        <br>
                                        <!-- <a href="{% url 'home:more'%}?item={{i.id}}" target="_blank"
                                            style="text-decoration: underline; font-weight: bold">More</a> -->
                                        <!-- <div class="learnmore">
                                        <a href="{% url 'home:more'%}?item={{i.id}}" target="_blank" class="btn btn-dark mt-5" role="button">View More </a>
                                    </div> -->
                                    </p>
                                    <a href="{% url 'home:more'%}?item={{i.id}}" class="btn btn-dark mt-5" role="button">
                                        <p class="text-light">View More</p>
                                    </a>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>


</section>
<!-- End Gallery Section -->
<!-- <script>
    $(document).ready(function () {
  $(".filter-button").click(function () {
    var value = $(this).attr("data-filter");
    // console.log("click");
    // console.log(value);
    if (value == "All") {
      $(".filter").removeClass("disable");
      $(".filter").show("1000");
    } else {
      //            $('.filter[filter-item="'+value+'"]').removeClass('hidden');
      //            $(".filter").not('.filter[filter-item="'+value+'"]').addClass('hidden');
      $(".filter").removeClass("disable");
      $(".filter")
        .not("." + value)
        .addClass("disable");
      $(".filter")
        .filter("." + value)
        .show("3000");
    }
  });

  if ($(".filter-button").removeClass("active")) {
    $(this).removeClass("active");
    $(this).removeClass("disable");
  }
  $(this).addClass("active");
});
</script> -->
{% endblock pagecontent %}

templates/render/portfolioitems.html
<div class="container-fluid" data-aos="fade-up">
    
    <div class="row g-0">
        
        <!-- Images with description example -->
        <!-- <section class="section pair">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                    </div>
                </div>
            </div>
        </section> -->
        
        {% for i in itemlist %}
        <div class="col-lg-3 col-md-4 filter print">
            <div class="gallery-item">
                <ul class="box-container">

                    <li class="box">
                        <div class="inner">
                            <a href="/assets/img/gallery/Portfolio 800x600-01.jpg" class="glightbox2"
                                data-glightbox="title: Description Right; description: .custom-desc1; descPosition: right;">
                                <img src="/assets/img/gallery/Portfolio 800x600-01.jpg" alt="image" />
                            </a>

                            <div class="glightbox-desc custom-desc1">
                                <p>
                                    You can set the position of the description in different ways for example
                                    <strong style="text-decoration: underline">top, bottom, left or
                                        right</strong>
                                </p>
                                <p>
                                    <a href="http://google.com" target="_blank"
                                        style="text-decoration: underline; font-weight: bold">Example Google
                                        link</a>
                                    ipsum vehicula eros ultrices lacinia Vestibulum ante ipsum primis in
                                    faucibus orci luctus et ultrices posuere cubilia Curae Duis quis ipsum
                                    vehicula eros ultrices lacinia.
                                    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere
                                </p>
                                <a href="item1.html" class="btn btn-dark mt-5" role="button">
                                    <p class="text-light">Learn More</p>
                                </a>
                            </div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
        {%endfor%}
    </div>
</div>